const pacientes = [
  {
    id: 1,
    nome_completo: "João Carlos da Silva",
    data_nascimento: "1950-03-12",
    idade: 75,
    sexo: "Masculino",
    quarto: "101A",
    unidade_internacao: "Clínica Médica",
    data_internacao: "2025-04-15",
    data_avaliacao_gicpel: "2025-04-16",
    alergias: "Dipirona",
    cor_pele: "Parda",
    altura: 1.68,
    peso: 72.5,
    imc: 25.7,
    motivo_internacao: "Pneumonia",
    comorbidades: ["HAS", "DM", "Doença Cardiovasculares"],
    medicamentos_uso: ["Antibiótico", "Hipoglicemiante oral", "Anticoagulante"],
  },
  {
    id: 2,
    nome_completo: "Maria Eduarda Costa",
    data_nascimento: "1985-11-22",
    idade: 39,
    sexo: "Feminino",
    quarto: "204B",
    unidade_internacao: "Oncologia",
    data_internacao: "2025-04-10",
    data_avaliacao_gicpel: "2025-04-11",
    alergias: "Nenhuma",
    cor_pele: "Branca",
    altura: 1.7,
    peso: 65.0,
    imc: 22.5,
    motivo_internacao: "Tratamento de Neoplasia",
    comorbidades: ["Neoplasia"],
    medicamentos_uso: ["Quimioterápico", "Antiemético", "Antibiótico"],
  },
  {
    id: 3,
    nome_completo: "Carlos Henrique Matos",
    data_nascimento: "1962-06-08",
    idade: 62,
    sexo: "Masculino",
    quarto: "310C",
    unidade_internacao: "Cirurgia Geral",
    data_internacao: "2025-04-20",
    data_avaliacao_gicpel: "2025-04-21",
    alergias: "Penicilina",
    cor_pele: "Negra",
    altura: 1.75,
    peso: 90.0,
    imc: 29.4,
    motivo_internacao: "Cirurgia abdominal",
    comorbidades: ["HAS", "Obesidade"],
    medicamentos_uso: ["Analgésico", "Antiinflamatório", "Antibiótico"],
  },
  {
    id: 4,
    nome_completo: "Ana Luísa Ferreira",
    data_nascimento: "2000-01-15",
    idade: 25,
    sexo: "Feminino",
    quarto: "122B",
    unidade_internacao: "Clínica Médica",
    data_internacao: "2025-04-12",
    data_avaliacao_gicpel: "2025-04-13",
    alergias: "Nenhuma",
    cor_pele: "Branca",
    altura: 1.65,
    peso: 58.0,
    imc: 21.3,
    motivo_internacao: "Infecção urinária",
    comorbidades: [],
    medicamentos_uso: ["Antibiótico"],
  },
  {
    id: 5,
    nome_completo: "José Roberto Lima",
    data_nascimento: "1975-09-03",
    idade: 49,
    sexo: "Masculino",
    quarto: "303D",
    unidade_internacao: "Cardiologia",
    data_internacao: "2025-04-18",
    data_avaliacao_gicpel: "2025-04-19",
    alergias: "AAS",
    cor_pele: "Parda",
    altura: 1.8,
    peso: 105.0,
    imc: 32.4,
    motivo_internacao: "Insuficiência cardíaca",
    comorbidades: ["HAS", "Obesidade", "Doença Cardiovasculares"],
    medicamentos_uso: ["Anticoagulante", "Antibiótico", "Analgésico"],
  },
  {
    id: 6,
    nome_completo: "Luciana Alves Brito",
    data_nascimento: "1992-04-17",
    idade: 33,
    sexo: "Feminino",
    quarto: "105A",
    unidade_internacao: "Neurologia",
    data_internacao: "2025-04-17",
    data_avaliacao_gicpel: "2025-04-18",
    alergias: "Nenhuma",
    cor_pele: "Branca",
    altura: 1.72,
    peso: 60,
    imc: 20.3,
    motivo_internacao: "AVC Isquêmico",
    comorbidades: ["HAS"],
    medicamentos_uso: ["Anticoagulante"],
  },
  {
    id: 7,
    nome_completo: "Fernando Luiz de Souza",
    data_nascimento: "1968-08-30",
    idade: 56,
    sexo: "Masculino",
    quarto: "301A",
    unidade_internacao: "Ortopedia",
    data_internacao: "2025-03-30",
    data_avaliacao_gicpel: "2025-04-01",
    alergias: "Ibuprofeno",
    cor_pele: "Negra",
    altura: 1.78,
    peso: 85.0,
    imc: 26.8,
    motivo_internacao: "Fratura de fêmur",
    comorbidades: ["DM"],
    medicamentos_uso: ["Antibiótico", "Analgésico"],
  },
  {
    id: 8,
    nome_completo: "Tatiane Meirelles Rocha",
    data_nascimento: "1990-06-12",
    idade: 34,
    sexo: "Feminino",
    quarto: "220B",
    unidade_internacao: "Maternidade",
    data_internacao: "2025-04-25",
    data_avaliacao_gicpel: "2025-04-26",
    alergias: "Nenhuma",
    cor_pele: "Branca",
    altura: 1.63,
    peso: 70,
    imc: 26.4,
    motivo_internacao: "Pré-natal de alto risco",
    comorbidades: ["HAS"],
    medicamentos_uso: ["Antiinflamatório", "Analgésico"],
  },
  {
    id: 9,
    nome_completo: "Rafael Torres Gomes",
    data_nascimento: "1988-12-05",
    idade: 36,
    sexo: "Masculino",
    quarto: "207C",
    unidade_internacao: "Psiquiatria",
    data_internacao: "2025-04-07",
    data_avaliacao_gicpel: "2025-04-08",
    alergias: "Nenhuma",
    cor_pele: "Parda",
    altura: 1.8,
    peso: 78,
    imc: 24.1,
    motivo_internacao: "Episódio depressivo grave",
    comorbidades: [],
    medicamentos_uso: ["Antidepressivo", "Analgésico"],
  },
  {
    id: 10,
    nome_completo: "Paula Regina Vasconcelos",
    data_nascimento: "1972-10-28",
    idade: 52,
    sexo: "Feminino",
    quarto: "118D",
    unidade_internacao: "Geriatria",
    data_internacao: "2025-04-02",
    data_avaliacao_gicpel: "2025-04-03",
    alergias: "Dipirona",
    cor_pele: "Branca",
    altura: 1.58,
    peso: 62,
    imc: 24.8,
    motivo_internacao: "Desidratação",
    comorbidades: ["HAS", "DM"],
    medicamentos_uso: ["Hipoglicemiante oral", "Antibiótico"],
  },
  {
    id: 11,
    nome_completo: "Bruno Almeida Santos",
    data_nascimento: "1995-07-23",
    idade: 29,
    sexo: "Masculino",
    quarto: "215C",
    unidade_internacao: "Clínica Cirúrgica",
    data_internacao: "2025-04-10",
    data_avaliacao_gicpel: "2025-04-11",
    alergias: "Nenhuma",
    cor_pele: "Negra",
    altura: 1.82,
    peso: 88,
    imc: 26.6,
    motivo_internacao: "Apendicite",
    comorbidades: [],
    medicamentos_uso: ["Antibiótico", "Analgésico"],
  },
  {
    id: 12,
    nome_completo: "Helena Duarte Pires",
    data_nascimento: "1983-02-11",
    idade: 42,
    sexo: "Feminino",
    quarto: "112A",
    unidade_internacao: "Reumatologia",
    data_internacao: "2025-04-08",
    data_avaliacao_gicpel: "2025-04-09",
    alergias: "Cetoprofeno",
    cor_pele: "Parda",
    altura: 1.6,
    peso: 63,
    imc: 24.6,
    motivo_internacao: "Artrite reumatoide",
    comorbidades: ["Outras"],
    medicamentos_uso: ["Antiinflamatório", "Analgésico"],
  },
  {
    id: 13,
    nome_completo: "Ricardo Neves Prado",
    data_nascimento: "1945-05-04",
    idade: 80,
    sexo: "Masculino",
    quarto: "109B",
    unidade_internacao: "Geriatria",
    data_internacao: "2025-03-28",
    data_avaliacao_gicpel: "2025-03-29",
    alergias: "Nenhuma",
    cor_pele: "Branca",
    altura: 1.7,
    peso: 60,
    imc: 20.8,
    motivo_internacao: "Queda em domicílio",
    comorbidades: ["HAS", "DAOP"],
    medicamentos_uso: ["Anticoagulante"],
  },
  {
    id: 14,
    nome_completo: "Isabela Cruz Mendes",
    data_nascimento: "1977-03-19",
    idade: 48,
    sexo: "Feminino",
    quarto: "223C",
    unidade_internacao: "Endocrinologia",
    data_internacao: "2025-04-03",
    data_avaliacao_gicpel: "2025-04-04",
    alergias: "Nenhuma",
    cor_pele: "Branca",
    altura: 1.55,
    peso: 78,
    imc: 32.5,
    motivo_internacao: "Descompensação diabética",
    comorbidades: ["DM", "Obesidade"],
    medicamentos_uso: ["Hipoglicemiante oral"],
  },
  {
    id: 15,
    nome_completo: "Thiago Ramos Farias",
    data_nascimento: "2001-09-09",
    idade: 23,
    sexo: "Masculino",
    quarto: "117A",
    unidade_internacao: "Psiquiatria",
    data_internacao: "2025-04-09",
    data_avaliacao_gicpel: "2025-04-10",
    alergias: "Nenhuma",
    cor_pele: "Parda",
    altura: 1.75,
    peso: 70,
    imc: 22.9,
    motivo_internacao: "Transtorno de ansiedade",
    comorbidades: [],
    medicamentos_uso: ["Ansiolítico"],
  },
  {
    id: 16,
    nome_completo: "Larissa Lopes Teixeira",
    data_nascimento: "1998-06-06",
    idade: 26,
    sexo: "Feminino",
    quarto: "130D",
    unidade_internacao: "Infectologia",
    data_internacao: "2025-04-20",
    data_avaliacao_gicpel: "2025-04-21",
    alergias: "Amoxicilina",
    cor_pele: "Branca",
    altura: 1.68,
    peso: 68,
    imc: 24.0,
    motivo_internacao: "Dengue com sinais de alarme",
    comorbidades: [],
    medicamentos_uso: ["Analgésico"],
  },
];

class PacienteController {
  static async obterPaciente(req, res) {
    try {
      const { id } = req.params;

      const paciente = pacientes.find((paciente) => paciente["id"] == id);

      res.status(200).json(paciente);
    } catch (error) {
      console.error(error);
      res.status(500).json({ erro: "Erro ao atualizar informações pessoais!" });
    }
  }

  static async carregarTodosPacientes(req, res) {
    try {
      res.status(200).json(pacientes);
    } catch (error) {
      console.error(error);
      res
        .status(500)
        .json({ erro: "Erro ao carregar informações dos pacientes!" });
    }
  }
}

export default PacienteController;
